version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      # Install dependencies
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv sync --extra docs

sphinx:
  configuration: docs/conf.py
