name: spherinator
channels:
  - conda-forge
dependencies:
  - jupytext
  - matplotlib
  - numpy
  - onnx
  - onnxruntime
  - pandas
  - pip
  - pip:
    - tensorrt
  - python=3.10
  - pytorch-gpu
  - lightning
  - scikit-image
  - scikit-learn
  - scipy
  - torchvision
