name: spherinator
channels:
  - conda-forge
dependencies:
  - healpy==1.16.5
  - jupytext==1.15.1
  - lightning==2.0.9
  - matplotlib==3.7.2
  - numpy==1.25.2
  - onnx==1.14.1
  - onnxruntime==1.15.1
  - pandas==2.1.0
  - pip==23.2.1
  - python==3.10.12
  - pytorch-gpu==2.0.0
  - scikit-image==0.21.0
  - scikit-learn==1.3.0
  - scipy==1.11.2
  - torchvision==0.15.2
  - wandb==0.15.10
  - pip:
    - ipykernel==6.25.2
    - jsonargparse[signatures]==4.24.1
    - tensorboard==2.14.0
    - tensorrt==8.6.1.post1
