[tool.pytest]
timeout = 300
testpaths = 'tests'

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore:The dataloader, train_dataloader, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument`",
]

[tool.pylint.TYPECHECK]
generated-members = 'numpy.*, torch.*'
