data:
  class_path: spherinator.data.ImagesDataModule
  init_args:
    data_directory: /hits/fast/its/doserbd/data/machine-learning/pokemon/
    extensions: ['jpg']
    image_size: 224
    batch_size: 32
    shuffle: True
    num_workers: 16
