data:
  class_path: spherinator.data.ShapesDataModule
  init_args:
    data_directory: /hits/basement/its/doserbd/projects/data/machine-learning/pink/shapes/
    shuffle: True
    image_size: 91
    batch_size: 32
    num_workers: 4