seed_everything: 42

model:
  class_path: models.RotationalVariationalAutoencoder
  init_args:
    h_dim: 256
    z_dim: 3
    distribution: "vmf"
    rotations: 36
    beta: 1.0

data:
  class_path: data.ShapesDataModule
  init_args:
    data_directory: /hits/basement/its/doserbd/projects/data/machine-learning/pink/shapes/
    batch_size: 32
    shuffle: True
    num_workers: 4
